#!/usr/bin/env python3
"""Topics part 2: remaining 361 topics (categories 7-20 plus extras)."""

# Continuation function - will be imported by main generator
def get_topics_part2():
    topics = []
    def add(slug, title, cat, kw, tools, img_tag):
        topics.append({"slug":slug,"title":title,"category":cat,"keywords":kw,"tools":tools.split(","),"img_tag":img_tag})

    add("ai-deal-intelligence-closing","AI Deal Intelligence for Closing","AI Sales","deal intelligence,closing","Gong AI,Clari,DealHub,Conga AI,Outreach","deals,closing")
    # AI FINANCE & ACCOUNTING (15)
    add("ai-accounting-automation-tools","AI Accounting Automation Tools","AI Finance","accounting automation,bookkeeping","QuickBooks AI,Xero AI,FreshBooks AI,Sage AI,Wave AI","accounting,finance")
    add("ai-tax-preparation-filing","AI Tax Preparation and Filing","AI Finance","tax preparation,tax filing ai","TurboTax AI,H&R Block AI,TaxAct AI,FreeTaxUSA,TaxSlayer","tax,filing")
    add("ai-financial-planning-advisors","AI Financial Planning for Advisors","AI Finance","financial planning,wealth mgmt","Wealthfront AI,Betterment AI,Personal Capital,Plaid AI,Addepar","finance,planning")
    add("ai-fraud-detection-banking","AI Fraud Detection for Banking","AI Finance","fraud detection,banking security","Feedzai,Featurespace,DataVisor,NICE Actimize,SAS AI","fraud,banking")
    add("ai-invoice-processing-ap","AI Invoice Processing Automation","AI Finance","invoice processing,accounts payable","Tipalti AI,Bill.com AI,AvidXchange,Stampli,Medius","invoice,payments")
    add("ai-credit-scoring-lending","AI Credit Scoring for Lending","AI Finance","credit scoring,lending ai","Zest AI,Upstart,Scienaptic,Pagaya,GiniMachine","credit,lending")
    add("ai-investment-portfolio-mgmt","AI Investment Portfolio Management","AI Finance","portfolio management,investing","Wealthfront AI,Betterment,Alpaca AI,QuantConnect,Kensho","investing,portfolio")
    add("ai-cryptocurrency-trading","AI Cryptocurrency Trading Tools","AI Finance","crypto trading,bitcoin ai","3Commas,Cryptohopper,Shrimpy AI,TradeSanta,Coinrule","crypto,trading")
    add("ai-expense-reporting-tools","AI Expense Reporting for Businesses","AI Finance","expense reporting,receipt ai","Expensify AI,Ramp AI,Brex,SAP Concur,Emburse","expense,reporting")
    add("ai-audit-compliance-tools","AI Audit and Compliance for Finance","AI Finance","audit ai,financial compliance","MindBridge AI,Caseware AI,TeamMate AI,AuditBoard,Workiva","audit,compliance")
    add("ai-budgeting-forecasting","AI Budgeting and Forecasting","AI Finance","budgeting ai,financial forecast","Anaplan AI,Adaptive Planning,Planful,Vena AI,Cube AI","budgeting,forecast")
    add("ai-payment-processing-tools","AI Payment Processing Optimization","AI Finance","payment processing,payments ai","Stripe AI,PayPal AI,Adyen,Checkout.com,Braintree","payments,processing")
    add("ai-accounts-receivable-tools","AI Accounts Receivable Management","AI Finance","accounts receivable,collections","YayPay AI,Billtrust,HighRadius,Esker AI,Versapay","receivable,collections")
    add("ai-financial-reporting-tools","AI Financial Reporting Dashboards","AI Finance","financial reporting,dashboards","Fathom AI,Jirav,Mosaic AI,Datarails,Spotlight Reporting","reporting,dashboards")
    add("ai-insurance-underwriting","AI Insurance Underwriting Tools","AI Finance","insurance underwriting,risk ai","Shift Technology,Tractable AI,Cape Analytics,CCC AI,Cytora","insurance,underwriting")
    # AI HR & RECRUITING (12)
    add("ai-resume-screening-ats","AI Resume Screening and ATS","AI HR","resume screening,ats ai","Greenhouse AI,Lever AI,iCIMS AI,Workday AI,SmartRecruiters","recruiting,ats")
    add("ai-interview-scheduling-tools","AI Interview Scheduling Tools","AI HR","interview scheduling,calendar ai","Calendly AI,GoodTime,ModernLoop,Cronofy,Paradox AI","interview,scheduling")
    add("ai-employee-engagement-tools","AI Employee Engagement Platforms","AI HR","employee engagement,pulse surveys","Culture Amp AI,Lattice AI,15Five AI,Peakon,Glint","engagement,culture")
    add("ai-performance-review-tools","AI Performance Review Systems","AI HR","performance review,feedback ai","Lattice AI,BetterWorks,Reflektive,ClearCompany,Leapsome","performance,review")
    add("ai-compensation-benchmarking","AI Compensation Benchmarking","AI HR","compensation ai,salary benchmark","Payscale AI,Salary.com AI,Compensation.BLR,CompTrak,Figures","compensation,salary")
    add("ai-workforce-planning-tools","AI Workforce Planning and Analytics","AI HR","workforce planning,hr analytics","Visier AI,Orgvue,ChartHop,Agentnoon,eQ8","workforce,planning")
    add("ai-diversity-inclusion-tools","AI Diversity and Inclusion Tools","AI HR","diversity ai,inclusion tools","Textio AI,Pymetrics,Blendoor,GapJumpers,Plum","diversity,inclusion")
    add("ai-talent-sourcing-platforms","AI Talent Sourcing Platforms","AI HR","talent sourcing,recruiting ai","SeekOut AI,HireEZ,hireflow,Fetcher,Entelo","talent,sourcing")
    add("ai-learning-development-lms","AI Learning and Development LMS","AI HR","learning management,lms ai","Docebo AI,Cornerstone AI,EdApp,360Learning,Lessonly","learning,development")
    add("ai-payroll-processing-tools","AI Payroll Processing Automation","AI HR","payroll ai,payroll automation","Gusto AI,Rippling AI,ADP AI,Paychex AI,Paylocity","payroll,hr")
    add("ai-exit-interview-retention","AI Exit Interview Analysis","AI HR","exit interview,retention ai","Medallia AI,Qualtrics AI,SurveyMonkey AI,Workday,Quantum Workplace","exit-interview,retention")
    add("ai-background-check-tools","AI Background Check and Screening","AI HR","background check,screening ai","Checkr AI,Sterling AI,GoodHire,HireRight AI,Accurate","background-check,screening")
    # AI LEGAL & COMPLIANCE (10)
    add("ai-contract-review-analysis","AI Contract Review and Analysis","AI Legal","contract review,legal analysis","Kira Systems,LawGeex,eBrevia,Luminance,ThoughtRiver","contract-review,legal")
    add("ai-legal-research-platforms","AI Legal Research Platforms","AI Legal","legal research,case law ai","Westlaw AI,LexisNexis AI,Casetext,ROSS Intelligence,vLex","legal-research,case-law")
    add("ai-patent-search-tools","AI Patent Search and Analysis","AI Legal","patent search,ip analysis","PatSnap AI,Innography,Anaqua AI,Clarivate AI,Google Patents AI","patent,intellectual-property")
    add("ai-regulatory-compliance","AI Regulatory Compliance Tools","AI Legal","regulatory compliance,regtech","Ascent AI,RegTech,Hummingbird,Compliance.ai,Suade","regulatory,compliance")
    add("ai-ediscovery-litigation","AI eDiscovery for Litigation","AI Legal","ediscovery,litigation ai","Relativity AI,Everlaw AI,Disco AI,Logikcull,Nuix","ediscovery,litigation")
    add("ai-privacy-data-protection","AI Privacy and Data Protection","AI Legal","privacy ai,data protection","OneTrust AI,BigID,Securiti AI,TrustArc,Collibra","privacy,data-protection")
    add("ai-trademark-monitoring","AI Trademark Monitoring Tools","AI Legal","trademark ai,brand protection","TrademarkNow,CompuMark AI,Corsearch,MarqVision,Clarivate","trademark,brand")
    add("ai-immigration-visa-tools","AI Immigration and Visa Processing","AI Legal","immigration ai,visa processing","Docketwise AI,Bridge US,LegalPad AI,SimpleCitizen,Boundless","immigration,visa")
    add("ai-will-estate-planning","AI Will and Estate Planning","AI Legal","estate planning,will ai","Trust & Will AI,Tomorrow,FreeWill,Willing,Gentreo AI","estate,planning")
    add("ai-legal-billing-time","AI Legal Billing and Time Tracking","AI Legal","legal billing,time tracking","Clio AI,PracticePanther,MyCase AI,Smokeball,CosmoLex","legal-billing,time")
    # AI MANUFACTURING & INDUSTRY (20)
    add("ai-predictive-maintenance-factory","AI Predictive Maintenance for Factories","AI Manufacturing","predictive maintenance,factory","Uptake AI,SparkCognition,Senseye,Augury,C3.ai","maintenance,factory")
    add("ai-quality-inspection-visual","AI Visual Quality Inspection","AI Manufacturing","quality inspection,visual ai","Landing AI,Cognex AI,Neurala,Instrumental,Elementary","inspection,quality")
    add("ai-robotics-warehouse-automation","AI Robotics for Warehouse Automation","AI Manufacturing","warehouse robotics,automation","Locus Robotics,6 River,Fetch Robotics,Geek+,Covariant","robotics,warehouse")
    add("ai-supply-chain-optimization","AI Supply Chain Optimization","AI Manufacturing","supply chain,optimization","o9 Solutions,Kinaxis,Blue Yonder,FourKites,E2open","supply-chain,optimization")
    add("ai-energy-management-industrial","AI Energy Management for Industry","AI Manufacturing","energy management,industrial","Schneider AI,Siemens AI,Honeywell AI,GE Digital,Enel X","energy,industrial")
    add("ai-digital-twin-manufacturing","AI Digital Twin for Manufacturing","AI Manufacturing","digital twin,simulation","Siemens Xcelerator,PTC AI,Ansys AI,Dassault AI,GE Digital Twin","digital-twin,simulation")
    add("ai-production-scheduling-tools","AI Production Scheduling","AI Manufacturing","production scheduling,planning","Siemens Opcenter,SAP AI,Oracle AI,Plex AI,DELMIA","production,scheduling")
    add("ai-welding-automation-tools","AI Welding Automation Tools","AI Manufacturing","welding ai,automation welding","Novarc AI,Weld AI,Path Robotics,Hirebotics,Miller AI","welding,automation")
    add("ai-cnc-machining-tools","AI CNC Machining Optimization","AI Manufacturing","cnc ai,machining optimization","Hexagon AI,Siemens NX,Autodesk AI,Mastercam AI,Haas AI","cnc,machining")
    add("ai-additive-manufacturing-3d","AI Additive Manufacturing 3D Printing","AI Manufacturing","3d printing ai,additive mfg","Materialise AI,Stratasys AI,3D Systems AI,Markforged,Desktop Metal","3d-printing,additive")
    add("ai-safety-monitoring-workplace","AI Workplace Safety Monitoring","AI Manufacturing","safety monitoring,workplace ai","Intenseye,Voxel AI,CompScience,Protex AI,Dataminr","safety,workplace")
    add("ai-demand-forecasting-mfg","AI Demand Forecasting for Manufacturing","AI Manufacturing","demand forecasting,manufacturing","Blue Yonder AI,o9 Solutions,ForecastX,John Galt,ToolsGroup","demand,forecasting")
    add("ai-inventory-optimization-mfg","AI Inventory Optimization","AI Manufacturing","inventory optimization,stock","EazyStock,Slimstock,Netstock,StockIQ,Relex Solutions","inventory,stock")
    add("ai-food-processing-quality","AI Food Processing Quality Control","AI Manufacturing","food processing,quality ai","TOMRA AI,Key Technology,KPM Analytics,Inspecto,Apeel Sciences","food,processing")
    add("ai-pharmaceutical-manufacturing","AI Pharmaceutical Manufacturing","AI Manufacturing","pharma manufacturing,gmp","Apprentice AI,Unchained Labs,Emerson AI,AspenTech,Sartorius AI","pharmaceutical,gmp")
    add("ai-textile-garment-production","AI Textile and Garment Production","AI Manufacturing","textile ai,garment production","Lectra AI,Gerber AI,Optitex,Tukatech,Clo Virtual","textile,garment")
    add("ai-automotive-manufacturing","AI Automotive Manufacturing Tools","AI Manufacturing","automotive ai,car production","Tesla AI,BMW AI,Siemens MOM,Rockwell AI,ABB Robotics","automotive,car")
    add("ai-chemical-process-optimization","AI Chemical Process Optimization","AI Manufacturing","chemical process,optimization","AspenTech AI,Honeywell AI,AVEVA AI,Yokogawa AI,Emerson AI","chemical,process")
    add("ai-packaging-automation-line","AI Packaging Line Automation","AI Manufacturing","packaging automation,line ai","Coesia AI,Bosch Packaging,Syntegon,ProMach AI,Krones AI","packaging,line")
    add("ai-equipment-monitoring-iot","AI Equipment Monitoring with IoT","AI Manufacturing","equipment monitoring,iot ai","PTC ThingWorx,Uptake,Samsara,MachineMetrics,Sight Machine","equipment,iot")
    # AI REAL ESTATE & PROPERTY (10)
    add("ai-property-valuation-tools","AI Property Valuation Tools","AI Real Estate","property valuation,appraisal","HouseCanary,Zillow Zestimate,CoreLogic,Redfin AI,Reonomy","property,valuation")
    add("ai-real-estate-lead-generation","AI Real Estate Lead Generation","AI Real Estate","real estate leads,agent marketing","CINC AI,BoomTown,Real Geeks,Ylopo,kvCORE","real-estate,leads")
    add("ai-property-management-tools","AI Property Management Platforms","AI Real Estate","property management,landlord ai","Buildium AI,AppFolio AI,RentRedi,TurboTenant,Avail","property-mgmt,landlord")
    add("ai-mortgage-lending-tools","AI Mortgage and Lending Tools","AI Real Estate","mortgage ai,lending tools","Blend AI,Roostify,ICE Mortgage,Tavant,LoanLogics","mortgage,lending")
    add("ai-commercial-real-estate","AI Commercial Real Estate Analytics","AI Real Estate","commercial real estate,analytics","Reonomy,CompStak,CoStar AI,Crexi AI,Propmodo","commercial,analytics")
    add("ai-home-inspection-tools","AI Home Inspection Tools","AI Real Estate","home inspection,property ai","Spectora AI,HomeGauge,InspectCheck,Imfuna,Palm-Tech","inspection,home")
    add("ai-real-estate-crm-tools","AI Real Estate CRM Solutions","AI Real Estate","real estate crm,agent crm","Follow Up Boss,LionDesk,Wise Agent,Realvolve,Contactually","real-estate-crm,agent")
    add("ai-rental-market-analysis","AI Rental Market Analysis","AI Real Estate","rental analysis,market data","Rentometer,Mashvisor,AirDNA,RentCafe,CoStar Rentals","rental,market")
    add("ai-smart-home-technology","AI Smart Home Technology","AI Real Estate","smart home,iot home","Google Nest,Amazon Echo,Samsung SmartThings,Apple HomeKit,Ecobee","smart-home,iot")
    add("ai-construction-project-mgmt","AI Construction Project Management","AI Real Estate","construction management,project","Procore AI,PlanGrid,Fieldwire,Autodesk BIM,Bluebeam","construction,project")
    # AI EDUCATION & LEARNING (15)
    add("ai-adaptive-learning-platforms","AI Adaptive Learning Platforms","AI Education","adaptive learning,personalized","DreamBox AI,ALEKS,Smart Sparrow,Knewton,Carnegie Learning","adaptive,learning")
    add("ai-language-learning-apps","AI Language Learning Applications","AI Education","language learning,language ai","Duolingo AI,Babbel AI,Rosetta Stone AI,Busuu,Mondly","language,learning")
    add("ai-tutoring-homework-help","AI Tutoring and Homework Help","AI Education","ai tutoring,homework help","Khan Academy AI,Chegg AI,Photomath,Socratic,Brainly","tutoring,homework")
    add("ai-classroom-management-tools","AI Classroom Management Tools","AI Education","classroom management,teacher ai","ClassDojo AI,Seesaw,Nearpod AI,Pear Deck,GoGuardian","classroom,teaching")
    add("ai-grading-assessment-tools","AI Grading and Assessment","AI Education","ai grading,assessment tools","Gradescope AI,Turnitin AI,Crowdmark,CodeGrade,Proctorio","grading,assessment")
    add("ai-curriculum-design-tools","AI Curriculum Design Tools","AI Education","curriculum design,lesson planning","Lesson.ai,Curipod,MagicSchool AI,TeachFX,Diffit","curriculum,lesson")
    add("ai-student-engagement-tools","AI Student Engagement Platforms","AI Education","student engagement,participation","Kahoot AI,Quizlet AI,Mentimeter,Slido,Poll Everywhere","engagement,student")
    add("ai-special-education-tools","AI Special Education and Accessibility","AI Education","special education,accessibility","Bookshare AI,Learning Ally,Texthelp,Kurzweil,Don Johnston","special-ed,accessibility")
    add("ai-stem-education-tools","AI STEM Education Tools","AI Education","stem education,coding ai","Code.org,Scratch AI,Tynker,CodeCombat,Brilliant","stem,coding")
    add("ai-higher-education-admin","AI Higher Education Administration","AI Education","higher education,university ai","Ellucian AI,Anthology,Civitas Learning,EAB,Mongoose","university,admin")
    add("ai-corporate-training-tools","AI Corporate Training Platforms","AI Education","corporate training,lms ai","Docebo AI,Cornerstone,EdApp,TalentLMS,Absorb LMS","corporate,training")
    add("ai-exam-proctoring-tools","AI Exam Proctoring Solutions","AI Education","exam proctoring,online testing","ProctorU AI,Proctorio,ExamSoft,Respondus,Honorlock","proctoring,exam")
    add("ai-research-paper-tools","AI Research Paper Discovery","AI Education","research papers,academic ai","Semantic Scholar,Connected Papers,Elicit AI,Consensus,Perplexity","research,papers")
    add("ai-music-education-tools","AI Music Education Tools","AI Education","music education,instrument ai","Yousician AI,Simply Piano,Flowkey,Fender Play,SmartMusic","music-ed,instrument")
    add("ai-early-childhood-edtech","AI Early Childhood Education Tech","AI Education","early childhood,preschool ai","Homer AI,Khan Academy Kids,ABCmouse AI,Osmo,HOMER","early-childhood,preschool")
    # AI E-COMMERCE & RETAIL (15)
    add("ai-product-recommendation-engines","AI Product Recommendation Engines","AI E-Commerce","product recommendations,ai","Algolia AI,Nosto,Recombee,Barilliance,Dynamic Yield","ecommerce,recommendations")
    add("ai-pricing-dynamic-retail","AI Dynamic Pricing for Retail","AI E-Commerce","dynamic pricing,retail ai","Prisync,Competera,Intelligence Node,Pricefx,Wiser","pricing,retail")
    add("ai-visual-search-shopping","AI Visual Search for Shopping","AI E-Commerce","visual search,image search ai","Syte AI,ViSenze,Google Lens,Pinterest Lens,Slyce","visual-search,shopping")
    add("ai-chatbot-customer-service","AI Chatbots for Customer Service","AI E-Commerce","chatbot ai,customer service","Zendesk AI,Intercom,Ada AI,Tidio,Freshchat","chatbot,customer-service")
    add("ai-inventory-retail-management","AI Inventory for Retail Management","AI E-Commerce","retail inventory,stock management","Brightpearl,TradeGecko,Cin7,Katana,inFlow","inventory,retail-mgmt")
    add("ai-personalization-ecommerce","AI Personalization for E-Commerce","AI E-Commerce","ecommerce personalization,ai","Dynamic Yield,Bloomreach,Monetate,Nosto,Emarsys","personalization,shopping")
    add("ai-returns-management-tools","AI Returns Management for E-Commerce","AI E-Commerce","returns management,reverse logistics","Loop Returns,Happy Returns,Returnly,AfterShip,Narvar","returns,logistics")
    add("ai-marketplace-sellers-tools","AI Tools for Marketplace Sellers","AI E-Commerce","marketplace selling,amazon ai","Jungle Scout AI,Helium 10,Sellics,Viral Launch,AMZScout","marketplace,amazon")
    add("ai-checkout-optimization","AI Checkout Optimization Tools","AI E-Commerce","checkout optimization,cart ai","Bold Commerce,Checkout.com AI,Fast,CartStack,Rebuy","checkout,cart")
    add("ai-demand-planning-retail","AI Demand Planning for Retail","AI E-Commerce","demand planning,forecasting","Blue Yonder,Relex Solutions,RELEX,Lokad,Anaplan","demand,retail")
    add("ai-customer-review-analysis","AI Customer Review Analysis","AI E-Commerce","review analysis,sentiment ai","Yotpo AI,Bazaarvoice,PowerReviews,Trustpilot AI,Birdeye","reviews,sentiment")
    add("ai-supply-chain-ecommerce","AI Supply Chain for E-Commerce","AI E-Commerce","supply chain,ecommerce logistics","ShipBob AI,Flexport,Shopify Fulfillment,Deliverr,FenixCommerce","supply-chain,fulfillment")
    add("ai-fraud-prevention-ecommerce","AI Fraud Prevention for E-Commerce","AI E-Commerce","fraud prevention,security ai","Signifyd,Riskified,Forter,Kount,ClearSale","fraud,security")
    add("ai-social-commerce-tools","AI Social Commerce Tools","AI E-Commerce","social commerce,shopping ai","Shopify AI,CommentSold,MikMak,Basketful,LikeToKnowIt","social-commerce,instagram")
    add("ai-subscription-ecommerce","AI Subscription Box E-Commerce","AI E-Commerce","subscription box,recurring ai","Recharge,Bold Subscriptions,Ordergroove,Recurly,Cratejoy","subscription,recurring")
    # AI AGRICULTURE & FARMING (10)
    add("ai-crop-monitoring-satellite","AI Crop Monitoring via Satellite","AI Agriculture","crop monitoring,satellite ai","Planet Labs,Descartes Labs,Taranis,Gamaya,CropX","crop,satellite")
    add("ai-precision-agriculture-tools","AI Precision Agriculture Tools","AI Agriculture","precision agriculture,farming ai","John Deere AI,Climate Corp,Trimble Ag,AgJunction,Raven","precision,farming")
    add("ai-livestock-monitoring-health","AI Livestock Monitoring and Health","AI Agriculture","livestock monitoring,animal ai","Cainthus,Cowlar,HerdDogg,Connecterra,SCR Dairy","livestock,cattle")
    add("ai-irrigation-water-management","AI Irrigation and Water Management","AI Agriculture","irrigation ai,water management","CropX,Netafim AI,Hortau,Ceres Imaging,Tule Technologies","irrigation,water")
    add("ai-soil-analysis-health","AI Soil Analysis and Health Tools","AI Agriculture","soil analysis,health ai","TerrAvion,Trace Genomics,Arable,SoilOptix,Agerpoint","soil,analysis")
    add("ai-pest-disease-detection","AI Pest and Disease Detection","AI Agriculture","pest detection,disease ai","Plantix,Peat GmbH,Agrio,Trapview,FarmSense","pest,disease")
    add("ai-farm-management-software","AI Farm Management Software","AI Agriculture","farm management,agtech","Granular,FarmLogs,Cropio,AgriWebb,Conservis","farm-mgmt,software")
    add("ai-agricultural-drones","AI Agricultural Drones","AI Agriculture","agricultural drones,crop spray","DJI Agriculture,AgEagle,PrecisionHawk,Sentera,DroneDeploy","drone,agriculture")
    add("ai-greenhouse-automation","AI Greenhouse Automation","AI Agriculture","greenhouse ai,controlled environment","iUNU,Motorleaf,Blue Radix,LettUs Grow,Infarm","greenhouse,controlled")
    add("ai-food-supply-traceability","AI Food Supply Chain Traceability","AI Agriculture","food traceability,supply chain","IBM Food Trust,FoodLogiQ,Ripe.io,TE-FOOD,Walmart Blockchain","food-supply,traceability")
    # AI CONSTRUCTION & ENGINEERING (10)
    add("ai-building-information-modeling","AI Building Information Modeling","AI Construction","bim ai,building modeling","Autodesk Revit AI,ArchiCAD AI,Bentley AI,Trimble,Tekla","bim,building")
    add("ai-construction-safety-tools","AI Construction Site Safety","AI Construction","construction safety,site ai","Smartvid.io,Newmetrix,viAct,Eyrus,SmartSight","safety,construction")
    add("ai-structural-engineering-tools","AI Structural Engineering Analysis","AI Construction","structural engineering,analysis","SAP2000 AI,ETABS AI,Robot Structural,STAAD.Pro,Tekla","structural,engineering")
    add("ai-construction-estimating","AI Construction Cost Estimating","AI Construction","cost estimating,construction","ProEst AI,PlanSwift,STACK AI,Sage Estimating,ConEst","estimating,cost")
    add("ai-project-scheduling-construction","AI Project Scheduling for Construction","AI Construction","project scheduling,timeline ai","Primavera AI,Microsoft Project AI,Procore,Buildertrend,CoConstruct","scheduling,timeline")
    add("ai-concrete-testing-materials","AI Concrete and Materials Testing","AI Construction","concrete testing,materials ai","Giatec AI,Converge,Hilti AI,Quipip,SmartRock","concrete,materials")
    add("ai-surveying-geospatial","AI Surveying and Geospatial","AI Construction","surveying ai,geospatial","DroneDeploy,Propeller Aero,Trimble AI,Leica AI,Topcon","surveying,geospatial")
    add("ai-hvac-optimization-tools","AI HVAC Design and Optimization","AI Construction","hvac ai,building systems","Brainbox AI,75F,Turntide,PassiveLogic,CopperTree","hvac,building-systems")
    add("ai-demolition-recycling","AI Demolition and Recycling","AI Construction","demolition ai,recycling","BROKK AI,Volvo CE AI,Caterpillar AI,ZenRobotics,AMP Robotics","demolition,recycling")
    add("ai-green-building-sustainability","AI Green Building and Sustainability","AI Construction","green building,sustainability","cove.tool,IES AI,OneClick LCA,Sefaira,GreenBadger","green-building,sustainability")
    # AI LOGISTICS & SUPPLY CHAIN (12)
    add("ai-route-optimization-delivery","AI Route Optimization for Delivery","AI Logistics","route optimization,delivery ai","OptimoRoute,Route4Me,Routific,WorkWave,Onfleet","delivery,route")
    add("ai-warehouse-management-wms","AI Warehouse Management Systems","AI Logistics","warehouse management,wms ai","Manhattan AI,Blue Yonder WMS,Körber AI,HighJump,Deposco","warehouse,management")
    add("ai-freight-rate-management","AI Freight Rate Management","AI Logistics","freight rates,shipping ai","Flexport AI,FreightWaves,DAT AI,Freightos,Emerge","freight,shipping")
    add("ai-last-mile-delivery","AI Last-Mile Delivery Optimization","AI Logistics","last mile,delivery optimization","Locus AI,FarEye,DispatchTrack,LogiNext,Bringg","last-mile,delivery")
    add("ai-customs-trade-compliance","AI Customs and Trade Compliance","AI Logistics","customs ai,trade compliance","Descartes AI,Amber Road,MIC,IntegrationPoint,C4T","customs,trade")
    add("ai-container-tracking-shipping","AI Container Tracking for Shipping","AI Logistics","container tracking,maritime","project44,FourKites,Vizion API,MarineTraffic,Windward AI","container,shipping")
    add("ai-cold-chain-monitoring","AI Cold Chain Monitoring","AI Logistics","cold chain,temperature ai","Sensitech,Emerson Cold Chain,Controlant,Tive,Roambee","cold-chain,temperature")
    add("ai-returns-reverse-logistics","AI Returns and Reverse Logistics","AI Logistics","reverse logistics,returns ai","Optoro,Happy Returns,ReverseLogix,G2 Reverse,12Return","returns,reverse")
    add("ai-demand-sensing-logistics","AI Demand Sensing for Logistics","AI Logistics","demand sensing,logistics ai","Blue Yonder,o9 Solutions,Logility,ToolsGroup,John Galt","demand,sensing")
    add("ai-fleet-telematics-tools","AI Fleet Telematics Tools","AI Logistics","fleet telematics,tracking","Samsara,Geotab,KeepTruckin,Lytx,Omnitracs","fleet,telematics")
    add("ai-carrier-selection-tools","AI Carrier Selection and Rating","AI Logistics","carrier selection,rating ai","ShipScience,ShipStation AI,EasyPost,Shippo,Pitney Bowes AI","carrier,selection")
    add("ai-cross-docking-optimization","AI Cross-Docking Optimization","AI Logistics","cross docking,distribution ai","Manhattan AI,JDA AI,Softeon,Fortna,Dematic AI","cross-docking,distribution")
    # AI HOSPITALITY & TOURISM (10)
    add("ai-hotel-revenue-management","AI Hotel Revenue Management","AI Hospitality","revenue management,hotel ai","IDeaS,Duetto,Atomize,RoomPriceGenie,Beyond Pricing","hotel,revenue")
    add("ai-restaurant-management-tools","AI Restaurant Management Tools","AI Hospitality","restaurant management,food ai","Toast AI,Square Restaurant,MarketMan,7shifts,Yelp AI","restaurant,food")
    add("ai-guest-experience-platforms","AI Guest Experience Platforms","AI Hospitality","guest experience,hospitality","Revinate,Alice,Whistle,GuestRevu,TrustYou","guest,experience")
    add("ai-travel-booking-engines","AI Travel Booking Engines","AI Hospitality","travel booking,reservation ai","Amadeus AI,Sabre AI,Travelport,Booking.com AI,Expedia AI","travel,booking")
    add("ai-food-waste-reduction","AI Food Waste Reduction in Hospitality","AI Hospitality","food waste,reduction ai","Winnow AI,Leanpath,Kitro,Lu