#!/usr/bin/env python3
"""Generate 500 topic definitions as JSON for the article builder."""
import json

topics = []

def add(slug, title, cat, kw, tools, img_tag):
    topics.append({"slug":slug,"title":title,"category":cat,"keywords":kw,"tools":tools.split(","),"img_tag":img_tag})

# AI WRITING & CONTENT (20)
add("ai-blog-writing-assistants-2026","Best AI Blog Writing Assistants for Professional Bloggers","AI Writing","ai blog writing,content assistant","Jasper,Writesonic,Copy.ai,Rytr,Anyword","writing,blog")
add("ai-copywriting-ecommerce-sales","AI Copywriting Tools That Boost E-Commerce Sales","AI Writing","ai copywriting,product descriptions","Jasper,Describely,Copysmith,Peppertype,Hypotenuse AI","ecommerce,shopping")
add("ai-academic-writing-research","AI Academic Writing Tools for Researchers","AI Writing","ai academic writing,research paper","Paperpal,Writefull,Trinka,Grammarly,QuillBot","academic,research")
add("ai-screenwriting-film-tv","AI Script Writing Tools for Film and TV","AI Writing","ai screenwriting,film script","Final Draft AI,Dramatron,ScriptBook,WriterSolo,NolanAI","film,cinema")
add("ai-technical-documentation-tools","AI Technical Writing for Software Documentation","AI Writing","technical writing,api docs","Document360,GitBook AI,Mintlify,Readme AI,Scribe","documentation,code")
add("ai-seo-content-writers","AI SEO Content Tools That Actually Rank","AI Writing","ai seo content,content optimization","Surfer SEO,Clearscope,MarketMuse,Frase,NeuronWriter","seo,search")
add("ai-newsletter-automation-tools","AI Newsletter Tools for Subscriber Growth","AI Writing","ai newsletter,email writing","Beehiiv AI,Substack AI,ConvertKit AI,Mailchimp AI,rasa.io","newsletter,email")
add("ai-social-caption-generators","AI Social Caption Generators for Engagement","AI Writing","ai captions,social writing","Lately AI,Predis.ai,Ocoya,Publer AI,Flick","social-media,caption")
add("ai-press-release-pr-tools","AI Press Release Writing for PR Pros","AI Writing","ai press release,pr writing","PRophet,Prowly AI,Muck Rack,Cision AI,Newswire AI","press,journalism")
add("ai-grant-proposal-nonprofits","AI Grant Proposal Writing for Nonprofits","AI Writing","ai grants,proposal generator","GrantScout,Instrumentl,OpenGrants,Fluxx AI,Submittable","nonprofit,grant")
add("ai-resume-cover-letter-tools","AI Resume Writers That Land Interviews","AI Writing","ai resume,cover letter ai","Teal AI,Kickresume,Rezi AI,Enhancv,Jobscan","resume,career")
add("ai-product-descriptions-stores","AI Product Description Generators","AI Writing","product descriptions,listing writer","Describely,Hypotenuse AI,Copysmith,Jasper,Writesonic","product,retail")
add("ai-translation-global-business","AI Translation for Global Businesses","AI Writing","ai translation,localization","DeepL Pro,Smartling,Phrase,Lokalise,Unbabel","translation,language")
add("ai-brand-storytelling-narrative","AI Storytelling for Brand Narratives","AI Writing","brand storytelling,narrative ai","Tome AI,Shorthand,Narrato,StoryChief,ContentBot","storytelling,brand")
add("ai-ghostwriting-book-authors","AI Ghostwriting Tools for Authors","AI Writing","ai ghostwriter,book writing","Sudowrite,NovelAI,ProWritingAid,Atticus,Reedsy","book,author")
add("ai-legal-document-drafting","AI Legal Writing for Contracts","AI Writing","legal writing,contract drafting","Harvey AI,CoCounsel,Lexis+ AI,Casetext,Spellbook","legal,contract")
add("ai-medical-clinical-writing","AI Medical Writing for Healthcare","AI Writing","medical writing,clinical docs","Nuance DAX,Notable Health,DeepScribe,Suki AI,Abridge","medical,healthcare")
add("ai-white-paper-b2b-content","AI White Paper Tools for B2B Leaders","AI Writing","white paper ai,b2b content","Writer.com,Acrolinx,PathFactory,Contently,Jasper","whitepaper,business")
add("ai-poetry-creative-writing-art","AI Poetry and Creative Writing Tools","AI Writing","ai poetry,creative writing","Verse by Verse,AI Dungeon,Sudowrite,Character.AI,NovelAI","poetry,creative")
add("ai-speech-writing-speakers","AI Speech Writing for Public Speakers","AI Writing","speech writer ai,presentation","Speeko AI,Orai,Yoodli,PromptSmart,Speechify","speech,presentation")
# AI VIDEO & MULTIMEDIA (20)
add("ai-video-editing-professionals","AI Video Editing for Professional Creators","AI Video","ai video editing,content creation","Premiere Pro AI,DaVinci Resolve,Descript,Runway ML,CapCut","video,editing")
add("ai-animation-beginners-guide","AI Animation for Beginners Without Design Skills","AI Video","ai animation,animated video","Animaker AI,Vyond,Powtoon,Renderforest,Steve AI","animation,cartoon")
add("ai-transcription-subtitle-tools","AI Transcription and Subtitle Tools","AI Video","ai transcription,subtitles","Otter.ai,Rev AI,Descript,Sonix,Happy Scribe","transcription,subtitle")
add("ai-deepfake-detection-media","AI Deepfake Detection for Media Verification","AI Video","deepfake detection,verification","Sensity AI,Video Authenticator,FakeCatcher,Deepware,Reality Defender","security,detection")
add("ai-music-video-indie-artists","AI Music Video Creation for Artists","AI Video","ai music video,indie artists","Kaiber AI,RunwayML,Luma AI,Pika Labs,Deforum","music,video")
add("ai-live-streaming-broadcast","AI Live Streaming for Broadcasters","AI Video","ai streaming,broadcast tools","StreamYard,Restream AI,OBS Plugins,Ecamm Live,vMix","streaming,broadcast")
add("ai-podcast-video-audiofirst","AI Podcast Video for Audio Creators","AI Video","ai podcast,video podcast","Riverside.fm,Squadcast,Descript,Podcastle,Zencastr","podcast,microphone")
add("ai-screen-recording-tutorials","AI Screen Recording for Tutorials","AI Video","screen recorder ai,tutorial maker","Loom AI,Tango,Scribe,Guidde,ScreenPal","screen,tutorial")
add("ai-3d-modeling-designers","AI 3D Modeling and Rendering","AI Video","ai 3d modeling,visualization","NVIDIA Omniverse,Meshy AI,Spline AI,Kaedim,Luma AI","3d,modeling")
add("ai-thumbnail-ctr-optimization","AI Thumbnails That Boost Click Rates","AI Video","ai thumbnails,ctr optimization","TubeBuddy,VidIQ,Canva AI,Snappa,PicMonkey","thumbnail,youtube")
add("ai-drone-aerial-cinematography","AI Drone Video for Aerial Cinematography","AI Video","drone video ai,aerial editing","Litchi AI,DJI Mimo,SkyPixel,AirMagic,DroneBase","drone,aerial")
add("ai-virtual-reality-creation","AI Virtual Reality Content Creation","AI Video","ai vr,virtual reality","Unity AI,Unreal Engine,Mozilla Hubs,Spatial.io,Virbela","vr,virtual-reality")
add("ai-augmented-reality-marketing","AI Augmented Reality for Marketing","AI Video","ai ar,augmented reality","Snap AR,Meta Spark,8thWall,Blippar,ZapWorks","ar,marketing")
add("ai-video-analytics-performance","AI Video Analytics for Content Performance","AI Video","video analytics,metrics ai","Tubular Labs,Wistia AI,Vidyard,Brightcove,SproutVideo","analytics,performance")
add("ai-personalized-video-sales","AI Personalized Video for Sales","AI Video","personalized video,sales outreach","Vidyard AI,BombBomb,Hippo Video,Loom,Sendspark","sales,personalization")
add("ai-documentary-indie-production","AI Documentary Tools for Producers","AI Video","ai documentary,film production","Blackmagic AI,Frame.io,Avid AI,Filmora AI,Kapwing","documentary,film")
add("ai-webinar-lead-generation","AI Webinar Tools for Lead Generation","AI Video","ai webinar,lead generation","Demio AI,WebinarJam,Livestorm,GoTo Webinar,Zoom AI","webinar,presentation")
add("ai-sports-video-coaching","AI Sports Video Analysis for Coaches","AI Video","sports analysis ai,coaching","Hudl AI,Catapult,Stats Perform,Second Spectrum,Veo","sports,athletics")
add("ai-real-estate-virtual-tours","AI Real Estate Virtual Tour Tools","AI Video","virtual tour ai,property listing","Matterport,Zillow 3D,CloudPano,EyeSpy360,iStaging","real-estate,property")
add("ai-educational-course-videos","AI Educational Video for Course Creators","AI Video","ai educational video,elearning","Synthesia,Colossyan,Elai.io,HeyGen,D-ID","education,course")
# AI DESIGN & CREATIVE (15)
add("ai-logo-brand-identity-tools","AI Logo Design for Brand Identity","AI Design","ai logo design,brand identity","Looka,Brandmark,Hatchful,Tailor Brands,Logo.ai","logo,brand")
add("ai-ux-prototyping-teams","AI UX Design and Prototyping","AI Design","ai ux design,prototyping","Figma AI,Uizard,Visily,Galileo AI,Framer AI","ux,prototype")
add("ai-fashion-design-apparel","AI Fashion Design for Apparel Industry","AI Design","ai fashion,clothing design","CLO 3D AI,Browzwear,Stylumia,Vue.ai,Resleeve","fashion,clothing")
add("ai-architectural-visualization","AI Architectural Visualization Tools","AI Design","ai architecture,rendering","ArkoAI,Maket AI,Spacemaker,TestFit,Midjourney","architecture,building")
add("ai-packaging-design-brands","AI Packaging Design for Brands","AI Design","ai packaging,label design","Packhelp AI,Esko AI,ePac AI,Arka,Packlane","packaging,product")
add("ai-infographic-data-viz","AI Infographic Creation for Data Viz","AI Design","ai infographic,data visualization","Canva AI,Venngage,Piktochart,Visme,Infogram","infographic,data")
add("ai-color-palette-generators","AI Color Palette Generators","AI Design","color palette ai,design colors","Coolors AI,Khroma,Colormind,Adobe Color,Muzli","color,palette")
add("ai-typography-font-selection","AI Typography and Font Tools","AI Design","ai typography,font selection","Fontjoy,Prototypo,Calligraphr,FontSelf,Google Fonts AI","typography,font")
add("ai-photo-restoration-enhance","AI Photo Restoration and Enhancement","AI Design","photo restoration,image enhance","Remini,MyHeritage AI,Topaz Photo AI,Luminar Neo,VanceAI","photo,restoration")
add("ai-interior-design-staging","AI Interior Design for Home Staging","AI Design","interior design ai,room viz","Planner 5D,HomeDesigns AI,RoomGPT,Havenly,Modsy","interior,home")
add("ai-illustration-digital-artists","AI Illustration for Digital Artists","AI Design","ai illustration,digital art","Midjourney,DALL-E 3,Stable Diffusion,Adobe Firefly,Leonardo AI","illustration,digital-art")
add("ai-motion-graphics-animation","AI Motion Graphics for Video Intros","AI Design","motion graphics ai,animation","After Effects AI,Jitter,Rive AI,LottieFiles,Cavalry","motion,graphics")
add("ai-social-media-graphics","AI Social Media Design Tools","AI Design","social design ai,brand graphics","Canva AI,Crello AI,Desygner,RelayThat,Snappa","social-media,branding")
add("ai-web-design-nocode-builders","AI Web Design No-Code Builders","AI Design","ai web design,no code","Wix ADI,Framer AI,Durable AI,10Web AI,Hostinger AI","website,nocode")
add("ai-print-marketing-materials","AI Print Design for Marketing","AI Design","print design ai,brochure maker","Canva AI,Lucidpress,Marq,DesignBold,PosterMyWall","print,marketing")
# AI MARKETING & SEO (25)
add("ai-email-marketing-conversions","AI Email Marketing for Higher Conversions","AI Marketing","ai email marketing,automation","Klaviyo AI,ActiveCampaign,Mailchimp AI,HubSpot AI,Drip","email,marketing")
add("ai-influencer-brand-partnerships","AI Influencer Marketing Platforms","AI Marketing","ai influencer,brand partnerships","Grin AI,CreatorIQ,Upfluence,AspireIQ,Traackr","influencer,social")
add("ai-content-strategy-b2b","AI Content Strategy for B2B Growth","AI Marketing","content strategy,b2b marketing","MarketMuse,Clearscope,BrightEdge,Conductor,PathFactory","content,strategy")
add("ai-ppc-advertising-roi","AI PPC Advertising for Maximum ROI","AI Marketing","ai ppc,advertising optimization","Optmyzr,WordStream AI,Adzooma,Acquisio,Albert AI","advertising,ppc")
add("ai-social-media-analytics-tools","AI Social Analytics for Marketing","AI Marketing","social analytics,data marketing","Sprout Social,Brandwatch,Hootsuite AI,Socialbakers,Talkwalker","social,analytics")
add("ai-seo-rank-tracking","AI SEO Rank Tracking Tools","AI Marketing","rank tracking,seo monitoring","SE Ranking,AccuRanker,SERPWatcher,Nozzle,AWR","seo,ranking")
add("ai-landing-page-conversion","AI Landing Pages for Conversions","AI Marketing","landing page ai,conversion","Unbounce AI,Instapage,Leadpages,Landingi,Swipe Pages","landing-page,conversion")
add("ai-market-research-intelligence","AI Market Research Tools","AI Marketing","market research,competitive intel","Crayon AI,Klue,Kompyte,SimilarWeb,Semrush","research,intelligence")
add("ai-customer-journey-ux","AI Customer Journey Mapping","AI Marketing","customer journey,experience","Salesforce Journey,Adobe Journey,Braze,Insider AI,CleverTap","customer,journey")
add("ai-ab-testing-optimization","AI A/B Testing for Websites","AI Marketing","ab testing,conversion testing","Optimizely,VWO AI,AB Tasty,Kameleoon,Convert AI","testing,optimization")
add("ai-chatbot-lead-qualification","AI Chatbots for Lead Qualification","AI Marketing","ai chatbot,lead qualification","Drift AI,Intercom AI,ManyChat,Tidio,Chatfuel","chatbot,leads")
add("ai-video-marketing-social","AI Video Marketing for Social","AI Marketing","video marketing,social ads","InVideo AI,Lumen5,Pictory,Synthesia,Promo AI","video,social-media")
add("ai-affiliate-passive-income","AI Affiliate Marketing Tools","AI Marketing","affiliate marketing,passive income","Voluum AI,ClickMagick,AffJet,Refersion,PartnerStack","affiliate,income")
add("ai-brand-reputation-monitoring","AI Brand Monitoring Tools","AI Marketing","brand monitoring,reputation","Brand24,Mention AI,Awario,ReviewTrackers,Birdeye","brand,reputation")
add("ai-local-seo-small-business","AI Local SEO for Small Business","AI Marketing","local seo,google business","BrightLocal,Whitespark,Moz Local,Yext AI,Semrush Local","local-seo,business")
add("ai-programmatic-media-buying","AI Programmatic Advertising","AI Marketing","programmatic ai,media buying","Trade Desk AI,DV360,MediaMath,Xandr,Basis AI","advertising,programmatic")
add("ai-customer-segmentation-targeting","AI Customer Segmentation Tools","AI Marketing","segmentation,audience targeting","Segment AI,Amplitude,Optimove,Dynamic Yield,Persado","segmentation,targeting")
add("ai-marketing-attribution-roi","AI Marketing Attribution Tools","AI Marketing","attribution,roi measurement","Triple Whale,Rockerbox,Northbeam,Windsor.ai,Attribution","attribution,analytics")
add("ai-voice-search-seo","AI Voice Search Optimization","AI Marketing","voice search,voice seo","AnswerThePublic,Semrush Voice,BrightEdge Voice,Schema App,Yext Voice","voice,search")
add("ai-predictive-campaign-success","AI Predictive Analytics for Campaigns","AI Marketing","predictive analytics,forecasting","Pecan AI,6sense,Leadspace,Mintigo,EverString","predictive,analytics")
add("ai-geo-targeting-location","AI Geo-Targeting for Marketing","AI Marketing","geo targeting,geofencing","Foursquare AI,GroundTruth,Factual,PlaceIQ,Near AI","location,targeting")
add("ai-content-distribution-reach","AI Content Distribution Platforms","AI Marketing","content distribution,syndication","Outbrain AI,Taboola AI,Quuu Promote,DrumUp,ContentStudio","distribution,reach")
add("ai-cro-ecommerce-tools","AI Conversion Optimization for E-Commerce","AI Marketing","cro ai,ecommerce optimization","Dynamic Yield,Nosto AI,Monetate,Certona,Barilliance","conversion,ecommerce")
add("ai-competitor-strategic-analysis","AI Competitor Analysis Tools","AI Marketing","competitor analysis,market intel","Crayon,Kompyte,SimilarWeb,SpyFu,iSpionage","competitor,analysis")
add("ai-podcast-marketing-growth","AI Podcast Marketing Tools","AI Marketing","podcast marketing,audio growth","Podscribe,Chartable,Buzzsprout AI,Transistor,CoHost","podcast,audio")
# AI BUSINESS & PRODUCTIVITY (25)
add("ai-project-management-enterprise","AI Project Management for Enterprise","AI Business","project management,enterprise","Monday.com AI,Asana AI,ClickUp AI,Wrike AI,Smartsheet","project,management")
add("ai-business-intelligence-data","AI Business Intelligence Tools","AI Business","business intelligence,bi tools","Tableau AI,Power BI AI,Looker AI,Sisense,ThoughtSpot","intelligence,data")
add("ai-workflow-automation-enterprise","AI Workflow Automation for Enterprise","AI Business","workflow automation,process","Zapier AI,Make.com,n8n,Power Automate,Workato","workflow,automation")
add("ai-document-management-paperless","AI Document Management Systems","AI Business","document management,paperless","DocuWare AI,M-Files,PandaDoc AI,Clio AI,SharePoint AI","document,office")
add("ai-customer-support-tickets","AI Customer Support Platforms","AI Business","customer support,helpdesk","Zendesk AI,Freshdesk AI,Intercom,Help Scout,Kayako","support,helpdesk")
add("ai-time-tracking-remote","AI Time Tracking for Remote Teams","AI Business","time tracking,productivity","Toggl AI,Clockify AI,RescueTime,DeskTime,Hubstaff","time-tracking,remote")
add("ai-inventory-forecasting-retail","AI Inventory Forecasting for Retail","AI Business","inventory forecasting,demand","Blue Yonder,Inventory Planner,StockTrim,Brightpearl,Linnworks","inventory,retail")
add("ai-virtual-assistant-operations","AI Virtual Assistants for Business","AI Business","virtual assistant,executive ai","x.ai,Clara AI,Reclaim AI,Motion AI,Clockwise","assistant,business")
add("ai-contract-lifecycle-legal","AI Contract Management Tools","AI Business","contract management,legal tech","Ironclad,Icertis,Agiloft,ContractPodAi,Juro","contract,legal")
add("ai-expense-corporate-finance","AI Expense Management Tools","AI Business","expense management,receipt scan","Brex AI,Ramp AI,Expensify AI,SAP Concur,Divvy","expense,finance")
add("ai-team-collaboration-distributed","AI Collaboration for Teams","AI Business","team collaboration,communication","Slack AI,Teams AI,Notion AI,Lark AI,Webex AI","collaboration,team")
add("ai-compliance-regulated-industries","AI Compliance Management","AI Business","compliance ai,regulatory","LogicGate,OneTrust,Compliance.ai,RegTech,Diligent","compliance,regulation")
add("ai-data-entry-elimination","AI Data Entry Automation","AI Business","data entry,form processing","Rossum AI,Nanonets,Docsumo,Parseur,Magical AI","data-entry,automation")
add("ai-business-plan-startups","AI Business Plan Generators","AI Business","business plan,startup planning","LivePlan AI,Bizplan,Enloop,PlanGuru,IdeaBuddy","startup,business-plan")
add("ai-knowledge-base-corporate","AI Knowledge Management Tools","AI Business","knowledge management,wiki","Guru AI,Notion AI,Tettra,Confluence AI,Slite","knowledge,learning")
add("ai-meeting-notes-transcription","AI Meeting Transcription Tools","AI Business","meeting notes,transcription","Otter.ai,Fireflies.ai,tl;dv,Avoma,Grain AI","meeting,notes")
add("ai-fleet-management-transport","AI Fleet Management Tools","AI Business","fleet management,vehicle tracking","Samsara AI,Fleetio,Geotab,Azuga,Verizon Connect","fleet,transport")
add("ai-quality-manufacturing-tools","AI Quality Management","AI Business","quality management,defect detect","InfinityQS,MasterControl,ETQ AI,Qualio,Greenlight Guru","quality,manufacturing")
add("ai-risk-enterprise-security","AI Risk Management Platforms","AI Business","risk management,threat assess","Resolver AI,MetricStream,Riskonnect,ProcessMAP,Galvanize","risk,security")
add("ai-procurement-sourcing","AI Procurement and Sourcing","AI Business","procurement ai,sourcing","Coupa AI,Jaggaer,Ivalua,GEP AI,SAP Ariba AI","procurement,sourcing")
add("ai-task-delegation-managers","AI Task Delegation for Managers","AI Business","task delegation,manager tools","Asana AI,ClickUp AI,Monday.com,Trello AI,Basecamp","task,management")
add("ai-employee-onboarding-hr","AI Employee Onboarding Tools","AI Business","onboarding ai,hr automation","BambooHR AI,Rippling AI,Gusto AI,WorkBright,Talmundo","onboarding,hr")
add("ai-sales-forecasting-revenue","AI Sales Forecasting Tools","AI Business","sales forecasting,revenue","Clari AI,Gong AI,InsightSquared,Aviso AI,BoostUp","forecasting,sales")
add("ai-supply-chain-visibility","AI Supply Chain Visibility","AI Business","supply chain,tracking","FourKites AI,project44,Transporeon,Descartes,BluJay","supply-chain,logistics")
add("ai-office-space-management","AI Office Space for Hybrid Work","AI Business","office management,hybrid","Robin AI,Envoy AI,OfficeSpace,Skedda,Teem AI","office,workspace")
# AI HEALTH & MEDICINE (15)
add("ai-diagnostic-imaging-radiology","AI Diagnostic Imaging for Radiology","AI Health","ai radiology,diagnostic imaging","Aidoc,Zebra Medical,Qure.ai,Viz.ai,Caption Health","radiology,medical")
add("ai-drug-discovery-pharma","AI Drug Discovery Platforms","AI Health","drug discovery,pharma research","Insilico Medicine,Atomwise,BenevolentAI,Recursion,Exscientia","pharma,research")
add("ai-mental-health-therapy","AI Mental Health Applications","AI Health","mental health ai,therapy","Woebot,Wysa,Talkiatry AI,Cerebral AI,BetterHelp AI","mental-health,therapy")
add("ai-patient-monitoring-remote","AI Remote Patient Monitoring","AI Health","patient monitoring,telehealth","Biofourmis,Current Health,Biobeat,PhysIQ,VitalConnect","monitoring,telehealth")
add("ai-clinical-trial-matching","AI Clinical Trial Matching","AI Health","clinical trials,recruitment","Deep 6 AI,TrialSpark,Antidote,Medidata AI,Veeva AI","clinical,research")
add("ai-electronic-health-records","AI Electronic Health Records","AI Health","ai ehr,health records","Epic AI,Cerner AI,Allscripts AI,athenahealth,DrChrono","health-records,ehr")
add("ai-surgical-robotics-tools","AI Surgical Robotics Tools","AI Health","ai surgery,robotic surgery","Intuitive AI,Medtronic AI,Stryker AI,Zimmer Biomet,CMR Surgical","surgery,robotics")
add("ai-pathology-lab-diagnostics","AI Pathology and Lab Diagnostics","AI Health","ai pathology,diagnostics","Paige AI,PathAI,Proscia,Hamamatsu AI,Roche AI","pathology,lab")
add("ai-telemedicine-virtual-care","AI Telemedicine for Virtual Care","AI Health","telemedicine ai,virtual visits","Teladoc AI,Amwell AI,MDLive AI,Doctor on Demand,PlushCare","telemedicine,virtual")
add("ai-nutrition-diet-planning","AI Nutrition and Diet Planning","AI Health","ai nutrition,diet planner","Nutrigenomix,Noom AI,MyFitnessPal AI,Lifesum AI,Ate AI","nutrition,diet")
add("ai-elderly-care-aging","AI Elderly Care and Aging Tech","AI Health","elderly care ai,aging tech","CarePredict,ElliQ,GrandPad AI,Best Buy Health,Vayyar","elderly,senior-care")
add("ai-dental-practice-tools","AI Tools for Dental Practices","AI Health","ai dental,dentistry tech","Overjet AI,Pearl AI,Dentistry.AI,VideaHealth,Denti.AI","dental,dentistry")
add("ai-fitness-personal-training","AI Fitness and Personal Training","AI Health","ai fitness,personal trainer","Tempo AI,Tonal AI,FitnessAI,Freeletics,Aaptiv","fitness,training")
add("ai-genomics-personalized-medicine","AI Genomics for Personalized Medicine","AI Health","ai genomics,precision medicine","Illumina AI,23andMe AI,Tempus,Foundation Medicine,Invitae","genomics,dna")
add("ai-hospital-operations-mgmt","AI Hospital Operations Management","AI Health","hospital management,operations","Qventus AI,LeanTaaS,Olive AI,Avia Health,Innovaccer","hospital,operations")
# AI SALES & CRM (20)
add("ai-sales-engagement-outbound","AI Sales Engagement for Outbound","AI Sales","sales engagement,outbound","Outreach AI,SalesLoft,Apollo.io,Mailshake,Reply.io","sales,engagement")
add("ai-crm-small-business","AI CRM for Small Business Growth","AI Sales","ai crm,small business","HubSpot AI,Zoho AI,Pipedrive AI,Freshsales,Capsule CRM","crm,business")
add("ai-lead-scoring-qualification","AI Lead Scoring Systems","AI Sales","lead scoring,qualification","MadKudu,Infer AI,Lattice Engines,6sense,Clearbit","lead-scoring,sales")
add("ai-sales-coaching-training","AI Sales Coaching Platforms","AI Sales","sales coaching,rep training","Gong AI,Chorus AI,ExecVision,Brainshark,Allego","coaching,training")
add("ai-proposal-generation-tools","AI Proposal Generation Tools","AI Sales","proposal ai,quote generator","PandaDoc AI,Proposify,Qwilr,Better Proposals,RFPIO","proposal,document")
add("ai-revenue-intelligence-tools","AI Revenue Intelligence","AI Sales","revenue intelligence,analytics","Gong AI,Clari,InsightSquared,People.ai,BoostUp","revenue,analytics")
add("ai-sales-territory-mapping","AI Sales Territory Mapping","AI Sales","territory planning,sales mapping","Salesforce Maps,Geopointe,MapAnything,Badger Maps,Maptive","territory,mapping")
add("ai-cold-email-outreach","AI Cold Email That Gets Responses","AI Sales","cold email,outreach automation","Lemlist AI,Instantly AI,Woodpecker,SmartReach,Snov.io","email,outreach")
add("ai-sales-enablement-content","AI Sales Enablement Tools","AI Sales","sales enablement,content mgmt","Seismic AI,Highspot,Showpad,Mindtickle,Bigtincan","enablement,content")
add("ai-pipeline-management-tools","AI Pipeline Management","AI Sales","pipeline management,deal tracking","Pipedrive AI,HubSpot Sales,Close AI,Freshsales,Copper","pipeline,deals")
add("ai-customer-success-retention","AI Customer Success Platforms","AI Sales","customer success,retention","Gainsight AI,Totango,ChurnZero,ClientSuccess,Catalyst","customer-success,retention")
add("ai-pricing-optimization-tools","AI Pricing Optimization","AI Sales","pricing optimization,dynamic","Prisync,Competera,Intelligence Node,Pricefx,PROS","pricing,optimization")
add("ai-sales-automation-workflow","AI Sales Automation Workflows","AI Sales","sales automation,workflow","Salesforce AI,HubSpot AI,Zoho AI,Freshworks AI,Keap","automation,sales")
add("ai-conversation-intelligence","AI Conversation Intelligence","AI Sales","conversation intelligence,call","Gong AI,Chorus AI,CallRail AI,Invoca,Jiminny","conversation,calls")
add("ai-account-based-marketing","AI Account-Based Marketing","AI Sales","account based marketing,abm","Demandbase,Terminus,RollWorks,6sense,Engagio","abm,b2b-marketing")
add("ai-sales-demo-tools","AI Sales Demo and Presentation","AI Sales","sales demo,product demo","Consensus AI,Demostack,Walnut,Reprise,Navattic","demo,presentation")
add("ai-customer-data-platforms","AI Customer Data Platforms","AI Sales","customer data,cdp","Segment,mParticle,Tealium,Treasure Data,ActionIQ","data-platform,customer")
add("ai-referral-program-tools","AI Referral Program Management","AI Sales","referral program,advocacy","ReferralCandy AI,Friendbuy,Ambassador,Extole,Referral Rock","referral,advocacy")
add("ai-subscription-management","AI Subscription Management","AI Sales","subscription management,recurring","Chargebee AI,Recurly,Zuora AI,Paddle,FastSpring","subscription,billing")